### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [nataliethenerd/picohatpad#1]
Hello!

I found this project from https://hackaday.com/2022/12/30/a-fun-low-cost-start-for-your-macropad-hobby/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and design files in any purpose?
It would be great to see any popular open source license.

**Comment by nataliethenerd** [comment]
apologies, I thought I added it! Done :)

**Comment by vazhnov** [comment]
MIT license — amazing!
@nataliethenerd, thank you!
